vich_uploader:
    db_driver: orm

    mappings:
       article_image:
          uri_prefix: /upload/articles
          upload_destination: '%kernel.project_dir%/public/upload/articles'
          namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

       products_image:
          uri_prefix: /upload/products
          upload_destination: '%kernel.project_dir%/public/upload/products'
          namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
  